server:
  port: 8090

spring:
  application:
    name: ERP_BE
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydb?
      useSSL=false&
      useUnicode=true&
      characterEncoding=utf8&
      allowMultiQueries=true&
      allowPublicKeyRetrieval=true&
      useLegacyDatetimeCode=false&
#      serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

mybatis-plus:
  mapper-locations: classpath:link/kongyu/erp/model/*/mapper/*Mapper.xml
  configuration:
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
    cache-enabled: true
    jdbc-type-for-null: NULL